# Generated by Django 5.2.4 on 2025-10-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('UN', 'Unidades'), ('KG', 'Kilogramos'), ('LB', 'Libras'), ('LT', 'Litros'), ('BX', 'Cajas'), ('PK', 'Paquetes'), ('M', 'Metros'), ('CM', 'Centímetros')], default='UN', max_length=10),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
