# Generated by Django 5.2.4 on 2025-10-14 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_unit_delete_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cost',
            new_name='price_sale',
        ),
    ]
