# Generated by Django 5.2.4 on 2025-10-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_cost_product_price_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_min',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
