# Generated by Django 5.2.4 on 2025-11-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
