# Generated by Django 5.2.8 on 2025-11-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryoutput',
            name='reason',
            field=models.CharField(choices=[('Transferencia entre sucursales', 'Transferencia entre sucursales'), ('Asignación a empleados', 'Asignación a empleados'), ('Devolución a proveedor', 'Devolución a proveedor'), ('Producto defectuoso', 'Producto defectuoso'), ('Donación', 'Donación'), ('Otro', 'Otro')], default='Otro', max_length=100),
        ),
    ]
