# Generated by Django 6.0.5 on 2026-05-13 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_inventoryoutput_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
    ]
