# Generated by Django 6.0.5 on 2026-05-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_expiration_date_remove_product_unit'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_brand_name_category',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_product_name_category'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
