# Generated by Django 5.2.4 on 2025-10-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_unique_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deadline_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
