# Generated by Django 5.2.4 on 2025-11-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_salepayment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Credito', 'Crédito')], default='Efectivo', max_length=13),
        ),
    ]
