# Generated by Django 5.2.4 on 2025-11-02 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_total_debt_alter_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_debt',
        ),
    ]
