# Generated by Django 6.0.5 on 2026-05-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_order_total_debt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity_value',
            new_name='quantity',
        ),
    ]
